server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: server-self

feign:
  client:
    config:
      default:
        connectTimeout: 5000 #单位毫秒
        readTimeout: 5000 #单位毫秒
        OkToRetryOnAllOperations: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 3
  # feign启用 hystrix
  hystrix:
    enabled: true

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 4
    # 为serviceB单独配置hystrix配置.
    serviceB:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 5
  # dashboard要开启这个允许的地址
  dashboard:
    proxyStreamAllowList: "localhost"



