server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: server-self

feign:
  client:
    config:
      default:
        connectTimeout: 5000 #单位毫秒
        readTimeout: 5000 #单位毫秒
        OkToRetryOnAllOperations: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 3
  # feign启用 hystrix
  hystrix:
    enabled: true

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000000
      circuitBreaker:
        requestVolumeThreshold: 4
    # 为serviceB单独配置hystrix配置.
    serviceB:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 5
  # dashboard要开启这个允许的地址
  dashboard:
    proxyStreamAllowList: "localhost"

turbine:
  appConfig: server-self  #turbine监控的服务，可以有多个: 注意, 这里监控的是注册在eureka 且 暴露出metrix的hystrix-service, 而不是真正的eureka作为consumer的服务.
                          # 所以, 每一个hystrix增强的生产者, 除了要暴露metrics之外, 还要把自己注册到eureka上面.
  clusterNameExpression: "'default'"
  instanceUrlSuffix:
    default: /actuator/hystrix.stream




